import type { PlaceSearchResult, PhotoAttribution } from '../types/models';

const apiKey=process.env.EXPO_PUBLIC_GOOGLE_PLACES_API_KEY;
export const hasGooglePlacesConfig=Boolean(apiKey);
const fields='places.id,places.displayName,places.formattedAddress,places.addressComponents,places.location,places.primaryType,places.primaryTypeDisplayName,places.rating,places.photos';
const detailFields='id,displayName,formattedAddress,addressComponents,location,primaryType,primaryTypeDisplayName,rating,photos';
function mapPlace(place:any):PlaceSearchResult{const photo=place.photos?.[0];const authors:PhotoAttribution[]=photo?.authorAttributions?.map((item:any)=>({displayName:item.displayName,uri:item.uri}))??[];const components=place.addressComponents??[];const area=components.find((part:any)=>part.types?.includes('sublocality_level_1'))?.longText??components.find((part:any)=>part.types?.includes('locality'))?.longText??'';const category=place.primaryTypeDisplayName?.text??place.primaryType?.replaceAll('_',' ')??'Food & drink';return {googlePlaceId:place.id??'',name:place.displayName?.text??'Unnamed place',address:place.formattedAddress??'',category,cuisine:category,area,latitude:place.location?.latitude,longitude:place.location?.longitude,googleRating:typeof place.rating==='number'?place.rating:undefined,photoUrl:photo?.name?`https://places.googleapis.com/v1/${photo.name}/media?maxWidthPx=1200&key=${apiKey}`:undefined,photoAttributions:authors,listReviewCount:0};}
async function request<T>(url:string,mask:string,body?:object):Promise<T>{const response=await fetch(url,{method:body?'POST':'GET',headers:{'X-Goog-Api-Key':apiKey!,'X-Goog-FieldMask':mask,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw new Error(`Google Places request failed (${response.status}). Check the API key and Places API (New) access.`);return response.json() as Promise<T>;}
export const googlePlaces={
 async search(query:string,origin:{latitude:number;longitude:number},radiusMeters:number):Promise<PlaceSearchResult[]>{if(!apiKey)throw new Error('Google Places is not configured.');const circle={center:origin,radius:radiusMeters};const result=query.trim()?await request<{places?:any[]}>('https://places.googleapis.com/v1/places:searchText',fields,{textQuery:query,includedType:'restaurant',pageSize:20,languageCode:'en',locationRestriction:{circle}}):await request<{places?:any[]}>('https://places.googleapis.com/v1/places:searchNearby',fields,{includedTypes:['restaurant'],maxResultCount:20,rankPreference:'DISTANCE',languageCode:'en',locationRestriction:{circle}});return (result.places??[]).map(mapPlace);},
 async getDetails(placeId:string):Promise<PlaceSearchResult>{if(!apiKey)throw new Error('Google Places is not configured.');return mapPlace(await request<any>(`https://places.googleapis.com/v1/places/${encodeURIComponent(placeId)}`,detailFields));},
};
