import { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { KeyboardAvoidingView, Platform, StyleSheet, View } from 'react-native';
import { BackButton, Button, Input, Page, Text } from '../components/ui';
import { firebaseAuth, signIn, signUp } from '../services/auth';
import { foodService } from '../services/foodService';
import { colors, radius, useTheme } from '../theme';

function friendlyError(error:unknown){const code=(error as {code?:string})?.code;if(code==='permission-denied'||code==='firestore/permission-denied')return'Firestore blocked your profile document. Deploy the latest firestore.rules in Firebase Console, then try again. If you just signed up, switch to Log In.';switch(code){case'auth/email-already-in-use':return'There is already an account with this email.';case'auth/invalid-email':return'Enter a valid email address.';case'auth/invalid-credential':case'auth/wrong-password':return'Email or password is incorrect.';case'auth/weak-password':return'Use a password with at least 6 characters.';case'auth/network-request-failed':return'Could not connect. Check your internet connection.';default:return error instanceof Error?error.message:'Authentication failed. Please try again.';}}
export default function AuthScreen(){useTheme();const s=makeStyles();const params=useLocalSearchParams<{returnTo?:string;mode?:string}>();const returnTo=Array.isArray(params.returnTo)?params.returnTo[0]:params.returnTo;const initialMode=Array.isArray(params.mode)?params.mode[0]:params.mode;const [creating,setCreating]=useState(initialMode==='create');const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(){setError('');if(!firebaseAuth){setError('Firebase Authentication is not configured. Add Firebase settings to .env and restart Expo.');return;}if(creating&&!name.trim()){setError('Enter your name.');return;}if(!email.trim()||!password){setError('Enter your email and password.');return;}if(creating&&password.length<6){setError('Use a password with at least 6 characters.');return;}setBusy(true);try{await (creating?signUp(name,email,password):signIn(email,password));await foodService.ensureCurrentUserProfile();const destination=returnTo?.startsWith('/review/')?returnTo:'/(tabs)';router.replace(destination as any);}catch(cause){setError(friendlyError(cause));}finally{setBusy(false);}}
 return <Page maxWidth={520}><View style={{flexDirection:'row',alignItems:'center',marginBottom:20}}><BackButton onPress={()=>router.back()}/><Text size={15} weight="600" style={{marginLeft:12}}>The List</Text></View><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1}}><Text size={13} weight="600" color={colors.green}>YOUR TABLE IS WAITING</Text><Text size={30} weight="700" style={{marginTop:7}}>{creating?'Create your account':'Welcome back'}</Text><Text size={14} color={colors.muted} style={{lineHeight:21,marginTop:7,marginBottom:25}}>{creating?'Join The List and keep your favourite places close.':'Sign in to write reviews and see your list.'}</Text>{creating&&<View style={s.field}><Text size={12} weight="600" style={s.label}>Name</Text><Input value={name} onChangeText={setName} autoComplete="name" placeholder="Your name" style={s.input}/></View>}<View style={s.field}><Text size={12} weight="600" style={s.label}>Email</Text><Input value={email} onChangeText={setEmail} autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="you@example.com" style={s.input}/></View><View style={s.field}><Text size={12} weight="600" style={s.label}>Password</Text><Input value={password} onChangeText={setPassword} secureTextEntry autoComplete={creating?'new-password':'current-password'} placeholder="At least 6 characters" style={s.input}/></View>{error?<Text size={12} color={colors.danger} style={{marginTop:8,lineHeight:18}}>{error}</Text>:null}<View style={{marginTop:24}}><Button title={busy?'Please wait…':creating?'Create account':'Log in'} loading={busy} disabled={busy} onPress={submit}/></View><Button title={creating?'Already have an account? Log in':'New to The List? Create an account'} variant="ghost" size="small" onPress={()=>{setCreating(!creating);setError('');}} style={{alignSelf:'center',marginTop:10}}/></KeyboardAvoidingView></Page>;
}
const makeStyles=()=>StyleSheet.create({field:{marginBottom:16},label:{marginBottom:7,color:colors.ink},input:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,paddingHorizontal:15,height:51,fontSize:15,color:colors.ink}});
