import { router, useFocusEffect } from 'expo-router';
import { useCallback } from 'react';
import { ImageBackground, StyleSheet, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Text, Button, Badge } from '../components/ui';
import { colors, radius } from '../theme';
import { watchAuthState } from '../services/auth';
import { isFirebaseRepositoryEnabled } from '../services/firebase';
export default function Welcome(){useFocusEffect(useCallback(()=>{if(!isFirebaseRepositoryEnabled)return;return watchAuthState(user=>{if(user)router.replace('/(tabs)');});},[]));const start=()=>router.replace(isFirebaseRepositoryEnabled?'/auth?mode=create':'/(tabs)');return <View style={s.root}><ImageBackground source={{uri:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1400&q=90'}} resizeMode="cover" style={s.hero}><View style={s.overlay}/><View style={s.top}><View style={s.mark}><Ionicons name="restaurant" size={19} color={colors.greenDark}/></View><Text size={13} weight="600" color={colors.white}>THE LIST · SYDNEY</Text></View><View style={s.copy}><Badge>GOOD FOOD, GOOD COMPANY</Badge><Text size={48} weight="700" color={colors.white} style={{lineHeight:53,marginTop:18}}>The List</Text><Text size={18} color="#F4F1E9" style={{lineHeight:27,marginTop:12,maxWidth:360}}>Discover great food through the people you trust.</Text><Button title="Get Started" icon="arrow-forward" variant="secondary" size="large" onPress={start} style={s.cta}/>{isFirebaseRepositoryEnabled&&<Button title="Log In" variant="ghost" size="small" onPress={()=>router.push('/auth')} style={{alignSelf:'flex-start',marginTop:12}}/>}</View></ImageBackground></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.greenDark},hero:{flex:1,justifyContent:'space-between',padding:28,paddingTop:54},overlay:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(24,39,29,0.58)'},top:{flexDirection:'row',alignItems:'center',gap:12,zIndex:1},mark:{width:39,height:39,borderRadius:13,backgroundColor:'#E5EBCF',alignItems:'center',justifyContent:'center'},copy:{zIndex:1,paddingBottom:30},cta:{marginTop:28,alignSelf:'flex-start',backgroundColor:'#E5EBCF',borderColor:'#E5EBCF'}});
