import React from 'react';
import { ActivityIndicator, Image, Platform, Pressable, ScrollView, StyleSheet, Text as NativeText, TextInput, View, type TextInputProps, type ViewStyle } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { ComponentProps } from 'react';
import { colors, radius, shadow, space } from '../theme';
import type { Place, Review, User } from '../types/models';
import { useTheme } from '../theme';
import { PressableScale } from './motion';

type IconName = ComponentProps<typeof Ionicons>['name'];
type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'destructive';
type ButtonSize = 'small' | 'medium' | 'large';

const buttonHeight: Record<ButtonSize, number> = { small: 40, medium: 48, large: 54 };
const buttonPadding: Record<ButtonSize, number> = { small: 14, medium: 18, large: 22 };
const buttonTextSize: Record<ButtonSize, number> = { small: 12, medium: 14, large: 15 };
const iconSizes: Record<ButtonSize, number> = { small: 16, medium: 18, large: 19 };

function buttonColors(variant: ButtonVariant) {
  if (variant === 'secondary') return { backgroundColor: colors.white, borderColor: colors.line, text: colors.ink, icon: colors.green };
  if (variant === 'ghost') return { backgroundColor: 'transparent', borderColor: 'transparent', text: colors.green, icon: colors.green };
  if (variant === 'destructive') return { backgroundColor: colors.danger, borderColor: colors.danger, text: colors.white, icon: colors.white };
  return { backgroundColor: colors.green, borderColor: colors.green, text: colors.white, icon: colors.white };
}

export function Text({ children, size=15, color=colors.ink, weight='400', style, numberOfLines }: any) { useTheme(); return <NativeText numberOfLines={numberOfLines} style={[{fontSize:size,color,fontWeight:weight as any,letterSpacing:0},style]}>{children}</NativeText>; }
export function Button({title,onPress,secondary=false,variant,size='medium',disabled=false,icon,loading=false,accessibilityLabel,style}: {title:string;onPress?:()=>void;secondary?:boolean;variant?:ButtonVariant;size?:ButtonSize;disabled?:boolean;icon?:IconName;loading?:boolean;accessibilityLabel?:string;style?:ViewStyle}) { useTheme(); const s=makeStyles(); const chosenVariant = variant ?? (secondary ? 'secondary' : 'primary'); const tone = buttonColors(chosenVariant); const inactive = disabled || loading; return <PressableScale disabled={inactive} onPress={onPress} accessibilityRole="button" accessibilityLabel={accessibilityLabel??title} accessibilityState={{disabled:inactive}} hoverStyle={chosenVariant === 'ghost' ? s.buttonGhostHover : s.buttonHover} style={[s.button,{height:buttonHeight[size],paddingHorizontal:buttonPadding[size],backgroundColor:tone.backgroundColor,borderColor:tone.borderColor},chosenVariant === 'ghost' && s.buttonGhost,inactive&&s.disabled,style]}>{loading?<ActivityIndicator size="small" color={tone.icon}/>:icon?<Ionicons name={icon} size={iconSizes[size]} color={tone.icon}/>:null}<Text size={buttonTextSize[size]} weight="700" color={tone.text}>{title}</Text></PressableScale>; }
export function IconButton({icon,onPress,label,variant='ghost',size='medium',disabled=false,style}: {icon:IconName;onPress?:()=>void;label:string;variant?:ButtonVariant;size?:ButtonSize;disabled?:boolean;style?:ViewStyle}) { useTheme(); const s=makeStyles(); const tone=buttonColors(variant); const dimension=buttonHeight[size]; return <PressableScale disabled={disabled} onPress={onPress} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled}} hitSlop={4} hoverStyle={variant==='ghost'?s.iconGhostHover:s.buttonHover} style={[s.iconButton,{width:dimension,height:dimension,borderRadius:dimension/2,backgroundColor:tone.backgroundColor,borderColor:tone.borderColor},disabled&&s.disabled,style]}><Ionicons name={icon} size={iconSizes[size]+1} color={tone.icon}/></PressableScale>; }
export function Card({children,style}: any) { useTheme(); const s=makeStyles(); return <View style={[s.genericCard,style]}>{children}</View>; }
export function Input(props: TextInputProps) { useTheme(); const s=makeStyles(); const webFocusReset=Platform.OS==='web'?({outlineStyle:'none',outlineWidth:0} as any):null; return <TextInput placeholderTextColor={props.placeholderTextColor ?? colors.muted} {...props} style={[s.inputField,webFocusReset,props.style]}/>; }
export function Avatar({user,size=42}: {user:User;size?:number}) { useTheme(); const s=makeStyles(); return <View style={[s.avatar,{width:size,height:size,borderRadius:size/2,backgroundColor:user.color,overflow:'hidden'}]}>{user.avatarUrl?<Image source={{uri:user.avatarUrl}} style={{width:size,height:size}}/>:<Text size={size*.32} weight="700" color={colors.white}>{user.initials}</Text>}</View>; }
export function Rating({value,size=14}: {value:number;size?:number}) { return <View style={{flexDirection:'row',alignItems:'center',gap:5}}><Ionicons name="star" size={size} color={colors.star}/><Text size={size} weight="700">{Number(value).toFixed(1)} / 10</Text></View>; }
export function Badge({children}:any) { useTheme(); const s=makeStyles(); return <View style={s.badge}><Text size={11} weight="600" color={colors.greenDark}>{children}</Text></View>; }
export function FilterChip({label,selected=false,onPress,onRemove,accessibilityLabel}: {label:string;selected?:boolean;onPress?:()=>void;onRemove?:()=>void;accessibilityLabel?:string}) { useTheme(); const s=makeStyles(); const Wrapper = onPress ? PressableScale : View; return <Wrapper accessibilityRole={onPress?'button':undefined as any} accessibilityState={onPress?{selected}:undefined as any} accessibilityLabel={accessibilityLabel ?? label} onPress={onPress as any} hoverStyle={s.chipHover} style={[s.filterChip,selected&&s.filterChipSelected] as any}><Text size={12} weight="700" color={selected?colors.white:colors.ink}>{label}</Text>{onRemove?<Pressable accessibilityRole="button" accessibilityLabel={`Remove ${label}`} hitSlop={8} onPress={onRemove}><Ionicons name="close" size={14} color={selected?colors.white:colors.greenDark}/></Pressable>:null}</Wrapper>; }
export function SearchBar({value,onChange,onFocus,onBlur,placeholder='Search places, dishes, areas'}:any) { useTheme(); const s=makeStyles(); return <View style={s.search}><Ionicons name="search" size={19} color={colors.muted}/><Input value={value} onChangeText={onChange} onFocus={onFocus} onBlur={onBlur} placeholder={placeholder} placeholderTextColor={colors.muted} style={s.searchInput}/>{value?<IconButton icon="close" label="Clear search" size="small" onPress={()=>onChange('')} style={s.searchClear}/>:null}</View>; }
export function PlaceCard({place,onPress,horizontal=false,cardWidth=254}: {place:Place;onPress:()=>void;horizontal?:boolean;cardWidth?:number}) { useTheme(); const s=makeStyles(); return <PressableScale onPress={onPress} accessibilityRole="button" accessibilityLabel={`Open ${place.name}`} hoverStyle={{borderColor:colors.green}} style={[s.placeCard,horizontal&&{width:cardWidth,marginRight:14}]}><Image source={{uri:place.image}} style={horizontal?s.placeImageWide:s.placeImage}/><View style={s.placeInfo}><View style={s.rowBetween}><Text size={17} weight="700" numberOfLines={1} style={{flex:1,marginRight:8}}>{place.name}</Text>{place.reviewCount>0?<View style={{alignItems:'flex-end'}}><Rating value={place.averageRating}/><Text size={10} color={colors.muted} style={{marginTop:3}}>{place.reviewCount} {place.reviewCount===1?'review':'reviews'}</Text></View>:<Text size={10} color={colors.muted}>No List reviews yet</Text>}</View><Text size={12} color={colors.muted} style={{marginTop:4}}>{place.cuisine??place.category} · {place.area}</Text>{place.googleRating!==undefined?<Text size={10} color={colors.muted} style={{marginTop:5}}>Google {place.googleRating.toFixed(1)}{place.googlePlaceId&&!place.googlePlaceId.startsWith('mock:')?' · Google Maps':''}</Text>:place.googlePlaceId&&!place.googlePlaceId.startsWith('mock:')?<Text size={10} color={colors.muted} style={{marginTop:5}}>Google Maps</Text>:null}</View></PressableScale>; }
export function ReviewCard({review}: {review:Review&{user:User}}) { useTheme(); const s=makeStyles(); const categories=Object.entries(review.subRatings??{}).filter((entry):entry is [string,number]=>typeof entry[1]==='number'); return <Card style={s.reviewCard}><View style={s.rowBetween}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><Avatar user={review.user} size={38}/><View><Text size={13} weight="600">{review.user.name}</Text><Text size={11} color={colors.muted} style={{marginTop:2}}>{review.date}</Text></View></View><Rating value={review.rating} size={13}/></View>{categories.length?<Text size={11} color={colors.muted} style={{marginTop:10}}>{categories.map(([key,value])=>`${key[0].toUpperCase()}${key.slice(1)} ${value}/10`).join('  ·  ')}</Text>:null}<Text size={14} color={colors.ink} style={{lineHeight:21,marginTop:12}}>{review.text}</Text></Card>; }
export function Page({children,scroll=true,maxWidth=920}:any) { useTheme(); const s=makeStyles(); const content=<View style={s.pageInner}>{children}</View>; return scroll?<ScrollView style={s.page} showsVerticalScrollIndicator={false} contentContainerStyle={{alignItems:'center'}}><View style={{width:'100%',maxWidth,overflow:'hidden'}}>{content}</View></ScrollView>:<View style={[s.page,{alignItems:'center'}]}><View style={{width:'100%',maxWidth,flex:1,overflow:'hidden'}}>{content}</View></View>; }
export function SectionTitle({title,action,onAction}:any) { useTheme(); const s=makeStyles(); return <View style={s.rowBetween}><Text size={19} weight="700">{title}</Text>{action&&<Button title={action} variant="ghost" size="small" onPress={onAction}/>}</View>; }
export function BackButton({onPress}:any) { useTheme(); return <IconButton icon="arrow-back" label="Go back" variant="secondary" onPress={onPress}/>; }
const makeStyles=()=>StyleSheet.create({genericCard:{backgroundColor:colors.white,borderRadius:radius.sm,padding:16,borderWidth:1,borderColor:colors.line,...shadow},inputField:{fontSize:15,color:colors.ink},page:{flex:1,backgroundColor:colors.paper},pageInner:{paddingHorizontal:space.xl,paddingTop:space.lg+2,paddingBottom:136,width:'100%'},button:{borderRadius:radius.pill,borderWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},buttonHover:{opacity:.92},buttonGhost:{paddingHorizontal:10},buttonGhostHover:{backgroundColor:colors.soft},iconButton:{borderWidth:1,alignItems:'center',justifyContent:'center'},iconGhostHover:{backgroundColor:colors.soft},disabled:{opacity:.45},avatar:{alignItems:'center',justifyContent:'center'},badge:{paddingHorizontal:10,paddingVertical:6,borderRadius:radius.pill,backgroundColor:colors.lime,alignSelf:'flex-start'},filterChip:{minHeight:40,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6,paddingHorizontal:13,borderRadius:radius.pill,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line},filterChipSelected:{backgroundColor:colors.green,borderColor:colors.green},chipHover:{borderColor:colors.green},search:{minHeight:52,borderRadius:radius.pill,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,flexDirection:'row',alignItems:'center',paddingLeft:16,paddingRight:8,gap:10},searchInput:{flex:1,fontSize:14,color:colors.ink},searchClear:{borderWidth:0,backgroundColor:'transparent'},placeCard:{width:'100%',borderRadius:radius.sm,backgroundColor:colors.white,overflow:'hidden',borderWidth:1,borderColor:colors.line,...shadow},placeImage:{width:'100%',height:170,backgroundColor:colors.soft},placeImageWide:{width:'100%',height:158,backgroundColor:colors.soft},placeInfo:{padding:14},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},reviewCard:{padding:16,marginTop:12}});





