import { useState } from 'react';
import { router, useFocusEffect } from 'expo-router';
import { useCallback } from 'react';
import { Image, View } from 'react-native';
import { useTheme, type ThemeMode } from '../../theme';
import { Avatar, Button, FilterChip, Page, Rating, SectionTitle, Text } from '../../components/ui';
import { PressableScale } from '../../components/motion';
import { foodService } from '../../services/foodService';
import { isFirebaseRepositoryEnabled } from '../../services/firebase';
import { signOutUser, watchAuthState } from '../../services/auth';
import type { Place, Review, User } from '../../types/models';
import { colors, radius } from '../../theme';

type MyReview = Review & { user: User; place: Place };
export default function ProfileScreen() {
 const {mode,setMode}=useTheme();
 const [user,setUser]=useState<User>(); const [myReviews,setReviews]=useState<MyReview[]>([]);const [authReady,setAuthReady]=useState(false);const [error,setError]=useState('');
 useFocusEffect(useCallback(()=>watchAuthState(authUser=>{setAuthReady(true);const id=authUser?.uid??(isFirebaseRepositoryEnabled?'':'u1');if(!id){setUser({id:'guest',name:'Guest',handle:'guest',initials:'G',color:'#8CA79A'});setReviews([]);return;}Promise.all([foodService.getUser(id),foodService.getCurrentUserReviews()]).then(([profile,rows])=>{setUser(profile);setReviews(rows);setError('');}).catch(cause=>setError(cause instanceof Error?cause.message:'Could not load your reviews.'));}),[]));
 return <Page><Text size={30} weight="700">Profile</Text><Text size={14} color={colors.muted} style={{marginTop:6,marginBottom:22}}>Your account and preferences.</Text>{user&&<View style={{flexDirection:'row',alignItems:'center',gap:14,padding:18,backgroundColor:colors.white,borderRadius:radius.md,borderWidth:1,borderColor:colors.line}}><Avatar user={user} size={60}/><View style={{flex:1}}><Text size={19} weight="700">{user.name}</Text><Text size={13} color={colors.muted} style={{marginTop:4}}>{myReviews.length} {myReviews.length===1?'review':'reviews'} shared</Text></View>{isFirebaseRepositoryEnabled&&user.id!=='guest'&&<Button title="Log out" variant="ghost" size="small" onPress={()=>signOutUser()}/>}</View>}{isFirebaseRepositoryEnabled&&authReady&&user?.id==='guest'?<View style={{marginTop:14}}><Button title="Log in or create an account" icon="person-outline" onPress={()=>router.push('/auth')}/></View>:null}{error?<Text size={12} color={colors.danger} style={{marginTop:12}}>{error}</Text>:null}<View style={{marginTop:26,marginBottom:10}}><SectionTitle title="Appearance"/></View><Text size={12} color={colors.muted} style={{marginBottom:10}}>Choose a theme or follow your device.</Text><View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}>{(['system','light','dark'] as ThemeMode[]).map(option=><FilterChip key={option} label={option==='system'?'System':option==='light'?'Light':'Dark'} selected={mode===option} onPress={()=>setMode(option)}/>)}</View><View style={{marginTop:28,marginBottom:12}}><SectionTitle title="Your reviews"/></View>{myReviews.length ? myReviews.map(review=><PressableScale key={review.id} accessibilityRole="button" accessibilityLabel={`Open ${review.place.name}`} hoverStyle={{borderColor:colors.green}} onPress={()=>router.push(`/place/${review.place.id}`)} style={{flexDirection:'row',padding:12,marginBottom:12,backgroundColor:colors.white,borderRadius:radius.sm,borderWidth:1,borderColor:colors.line,gap:13}}><Image source={{uri:review.place.image}} style={{width:82,height:82,borderRadius:8,backgroundColor:colors.soft}}/><View style={{flex:1,justifyContent:'center'}}><Text size={16} weight="700">{review.place.name}</Text><View style={{marginTop:5}}><Rating value={review.rating}/></View>{review.place.googlePlaceId&&!review.place.googlePlaceId.startsWith('mock:')?<Text size={9} color={colors.muted} numberOfLines={1} style={{marginTop:4}}>{review.place.photoAttributions?.[0]?`Photo: ${review.place.photoAttributions[0].displayName} · `:''}Google Maps</Text>:null}<Text numberOfLines={2} size={12} color={colors.muted} style={{marginTop:6,lineHeight:17}}>{review.text}</Text></View></PressableScale>):<View style={{padding:24,backgroundColor:colors.white,borderRadius:radius.md,alignItems:'center'}}><Text size={15} weight="600">Your List starts with a meal</Text><Text size={13} color={colors.muted} style={{marginTop:6,textAlign:'center'}}>Leave a review to help your people find somewhere good.</Text></View>}</Page>;
}
